version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "gitlab.com/metahkg/forks-imgpush-zqwoyd"

[[analyzers]]
name = "docker"

[[transformers]]
name = "gofmt"