stages:
  - lint
  - test
  - build
  - deploy
  - review
  - dast
  - fuzz
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker pull tonistiigi/binfmt:latest
    - docker run --privileged --rm tonistiigi/binfmt --uninstall qemu-*
    - docker run --privileged --rm tonistiigi/binfmt --install all
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker buildx create --use
    - docker buildx build -f Dockerfile --push --pull --platform linux/amd64,linux/arm64
       -t "${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}:latest"
       -t "${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}" .
    - if [ "$CI_COMMIT_BRANCH" = "master" ]; then
       docker buildx build -f Dockerfile --push --pull --platform linux/amd64,linux/arm64
       -t "${CI_REGISTRY_IMAGE}:latest" .; fi;
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $PULL != "true"
      exists:
        - Dockerfile

pull:
  image: alpine:latest
  before_script:
    - apk add git
    - git checkout master
    - git remote set-url origin https://root:$gitlab_token@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git remote add upstream https://github.com/hauxir/imgpush || git remote set-url upstream https://github.com/hauxir/imgpush
    - git config --global user.email "bot@metahkg.org"
    - git config --global user.name "metahkg-bot"
    - git config pull.rebase false
    - git pull origin master
  script:
    - |
      git fetch upstream
      git merge -X theirs upstream/master -m "Pull upstream" --allow-unrelated-histories
      git push origin --all
  rules:
    - if: $PULL == "true"

test:
  stage: test
  allow_failure: true

build:
  stage: build
  allow_failure: true

include:
  - template: Auto-DevOps.gitlab-ci.yml
    rules:
      - if: $PULL != "true"
