version: '3.5'
services:
  imgpush:
    image: imgpush
    ports:
        - "5001:5000"
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      MONGO_URI: mongodb://imgpush-mongo
      USE_MONGO: True
    volumes:
      - ./images:/images:Z
      - ./cache:/cache:Z
    networks:
      - imgpush-network
  mongo:
    image: ${MONGO_IMAGE:-mongo:6.0}
    container_name: imgpush-mongo
    ports:
      - "27018:27017"
    restart: unless-stopped
    networks:
      - imgpush-network
    volumes:
        - ./data:/data/db
networks:
  imgpush-network:
    driver: bridge
