version: '3.5'
services:
  imgpush:
    image: imgpush
    ports:
        - "5000:5000"
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      MONGO_URI: mongodb://imgpush-mongo
      USE_MONGO: True
    volumes:
      - ./images:/images:Z
      - ./cache:/cache:Z
    networks:
      - imgpush-network
  mongo:
    image: ${MONGO_IMAGE:-mongo:6.0}
    container_name: imgpush-mongo
    restart: always
    networks:
      - imgpush-network
networks:
  imgpush-network:
    driver: bridge
